### ISSUE TITLE
Unable to pass filters to trends api

### ISSUE THREAD

**Issue by cconstantine** [bugsnag/bugsnag-api-ruby#12]
https://github.com/bugsnag/bugsnag-api-ruby/blob/33efe3047294ded70848c860433296c0224f4d5f/lib/bugsnag/api/client/trends.rb#L27

The trends api takes a filter parameter to allow you to narrow down the trends request, but because the `options` hash is merged with a `{:query => {:resolution => resolution}}` it's impossible to add query parameters to the request.  

I have a workaround, but it involves building my own options hash and making the call like this: `::Bugsnag::Api.get("projects/#{project["id"]}/trend", options)`

**Comment by Cawllec** [comment]
Good catch, I'll get this and any other similar instances fixed and pushed out soon.
