### ISSUE TITLE
Base href bug with pagination and custom endpoint

### ISSUE THREAD

**Issue by ggilder** [bugsnag/bugsnag-api-ruby#4]
If I configure the Bugsnag API client with a custom endpoint and auto pagination, it appears that the pagination links revert to `http://localhost` as the base href:

``` ruby
client = Bugsnag::Api::Client.new(
  auth_token: "[TOKEN]",
  endpoint: "http://bugsnag.mycompany.com",
  auto_paginate: true,
  per_page: 100,
)
client.error_events('[ERROR_ID]')
# => Bugsnag::Api::ServiceUnavailable: GET http://localhost/errors/[ERROR_ID]/events?direction=desc&offset=54f889aa3c83d80c1110fd12&per_page=100&sort=received_at: 503 - from /Users/gabriel/.rvm/gems/ruby-2.1.2/gems/bugsnag-api-1.0.2/lib/bugsnag/api/response/raise_error.rb:16:in `on_complete'
```

**Comment by ggilder** [comment]
cc @loopj

**Comment by snmaynard** [comment]
@ggilder is this with your internal bugsnag instance? Its more likely to be a serverside issue than in the lib itself.

**Comment by ggilder** [comment]
Yep, internal instance. Should I just email in a bug report then?

**Comment by snmaynard** [comment]
This has been fixed a long time ago on the server side and dropped through the cracks - closing.
