### ISSUE TITLE
Bugsnag::Api.organization fails on organization-id

### ISSUE THREAD

**Issue by johnstotler** [bugsnag/bugsnag-api-ruby#46]
### Describe the bug
Getting organizations appears to be broken when following the readme

### Steps to reproduce
1. Authenticate
2. Run org = Bugsnag::Api.organization("organization-id")

### Environment
* Ruby version: ruby 2.7.7p221
### Example code snippet

```
require 'bugsnag/api'

Bugsnag::Api.configure do |config|
  config.auth_token = "<token>"
end

org = Bugsnag::Api.organization("organization-id")

```

<details><summary>Error messages:</summary>

```
parse_query_and_convenience_headers': undefined method `fetch' for "organization-id":String (NoMethodError)
```
</details>

**Comment by clr182** [comment]
Hi @johnstotler 

Can you confirm that you are using the correct `auth_token` value? please verify you are using the authentication token found at 'Dashboard > Settings > My account > Personal auth tokens' and not a project API key.

It may also be worth generating a new token and using that token in your `config.auth_token`.

**Comment by mclack** [comment]
Hi @johnstotler 

As there hasn't been any activity here for a while, we are now closing this issue.

If you continue experiencing problems, then please feel free to reopen this issue and share any additional relevant information. Or you can open a ticket with us directly by contacting [support@bugsnag.com](mailto:support@bugsnag.com).
