### ISSUE TITLE
Deploys API

### ISSUE THREAD

**Issue by mcasper** [bugsnag/bugsnag-api-ruby#7]
Hey guys,

You allow the user to register deploys through your notifier API, making reports like 'Errors introduced in the latest deploy' possible. I was wondering if you were planning on making a read API available for registered deploys? Presumably just the index/show endpoints, it would be great to have this for external reporting of bugs/deploy.

If the API already exists and is just undocumented, or if it were to be built, I would be happy to open a PR adding the functionality to this repo.

**Comment by phillipsam** [comment]
Hi @mcasper  - we now have an API which will allow you to list releases : https://bugsnagapiv2.docs.apiary.io/#reference/projects/releases/list-releases-on-a-project

Can you please confirm if this meets your needs described above?

**Comment by mcasper** [comment]
Yeah, that should work 👍
